[package]
name = "jkbase-proxy"
version = "0.1.0"
edition = "2024"

[dependencies]
jkbase-common = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
hyper = { workspace = true, features = ["client", "server", "http1"] }
hyper-util = { workspace = true, features = ["tokio", "client-legacy", "server-auto"] }
http-body-util = { workspace = true }
tracing = { workspace = true }
rustls = { workspace = true }
tokio-rustls = { workspace = true }
instant-acme = { workspace = true }
rcgen = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
reqwest = { workspace = true }
rustls-pemfile = { workspace = true }
