[package]
name = "jkbase-cli"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "jkbase"
path = "src/main.rs"

[dependencies]
jkbase-common = { workspace = true }
clap = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
reqwest = { workspace = true }
flate2 = { workspace = true }
tar = { workspace = true }
dirs = "6"
