[package]
name = "jkbase-server"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "jkbase-server"
path = "src/main.rs"

[dependencies]
jkbase-common = { workspace = true }
jkbase-proxy = { workspace = true }
jkbase-wsproxy = { workspace = true }
jkbase-control = { workspace = true }
jkbase-orch = { workspace = true }
jkbase-substrate = { workspace = true }
jkbase-objectstore = { workspace = true }
jkbuild-types = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
sha2 = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
axum = { workspace = true }
clap = { workspace = true }
rustls = { workspace = true }
tokio-rustls = { workspace = true }
rcgen = { workspace = true }
reqwest = { workspace = true }
time = "0.3"
hyper = { workspace = true }
hyper-util = { workspace = true }
http-body-util = { workspace = true }
cron = { workspace = true }
chrono = { workspace = true }
flate2 = { workspace = true }
tar = { workspace = true }
tower = { workspace = true, features = ["util"] }
tower-http = { version = "0.6", features = ["cors"] }
tokio-util = { workspace = true }
futures-util = { workspace = true }

[dev-dependencies]
toml = { workspace = true }
rustls-pemfile = { workspace = true }
