[package]
name = "jkbase-control"
version = "0.1.0"
edition = "2024"

[dependencies]
jkbase-common = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
axum = { workspace = true }
redb = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
flate2 = { workspace = true }
tar = { workspace = true }
argon2 = { workspace = true }
base64 = { workspace = true }
hmac = { workspace = true }
sha2 = { workspace = true }
tower-http = { version = "0.6", features = ["cors"] }
hyper = { workspace = true }
hyper-util = { workspace = true }
http-body-util = { workspace = true }
reqwest = { workspace = true }
cron = { workspace = true }
chrono = { workspace = true }
