[project]
name = "server-test"

[hosting]
public = "public"
spa = false

[servers.api]
dockerfile = "./Dockerfile"
port = 8080

[servers.api.health_check]
path = "/health"
interval = "10s"
timeout = "5s"

[routes]
"/api/*" = { service = "server", name = "api" }
